### ISSUE TITLE
AuthenticationApi.login() exception - TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by namgivu** [docusign/docusign-python-client#10]
I followed sample code in README.md and [pushed at this commit](https://github.com/namgivu/docusign-start/commit/278c6eb16d6c7d8559345ade4fcb87f9e1efb062) though it resulted with error as below.

[The fix](https://stackoverflow.com/a/42683509/248616) is to edit **docusign_esign/api_client.py**
from 
```
data = json.loads(response.data)
```
to
```
data = json.loads(response.data.decode('utf-8'))
```
After edited, run again and it succeeded. So do we need a fork for that fix?

I'm new to DocuSign and I don't know if I did something wrong so I raise it here. Please shed light on me.
Regards,
Nam

The error trace
```
    Traceback (most recent call last):
      File "/home/namgivu/NN/code/_NN_/docusign-start/run00.py", line 66, in <module>
        login_info = auth_api.login(api_password='true', include_account_id_guid='true')
      File "/home/namgivu/NN/code/_NN_/docusign-start/venv3/lib/python3.5/site-packages/docusign_esign/apis/authentication_api.py", line 388, in login
        (data) = self.login_with_http_info(**kwargs)
      File "/home/namgivu/NN/code/_NN_/docusign-start/venv3/lib/python3.5/site-packages/docusign_esign/apis/authentication_api.py", line 472, in login_with_http_info
        collection_formats=collection_formats)
      File "/home/namgivu/NN/code/_NN_/docusign-start/venv3/lib/python3.5/site-packages/docusign_esign/api_client.py", line 373, in call_api
        _return_http_data_only, collection_formats, _preload_content, _request_timeout)
      File "/home/namgivu/NN/code/_NN_/docusign-start/venv3/lib/python3.5/site-packages/docusign_esign/api_client.py", line 208, in __call_api
        return_data = self.deserialize(response_data, response_type)
      File "/home/namgivu/NN/code/_NN_/docusign-start/venv3/lib/python3.5/site-packages/docusign_esign/api_client.py", line 282, in deserialize
        data = json.loads(response.data)
      File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
        s.__class__.__name__))
    TypeError: the JSON object must be str, not 'bytes'    
```

**Comment by mmallis87** [comment]
The fix is scheduled for today.

**Comment by mmallis87** [comment]
the fix was deployed with 1.0.3 version today.

**Comment by namgivu** [comment]
Great speed. Thank you @mmallis87

**Comment by mmallis87** [comment]
@namgivu You got it. Sorry for the delay!
