### ISSUE TITLE
GET Template calls failing

### ISSUE THREAD

**Issue by excenter** [docusign/docusign-python-client#33]
Template get (a call I've made hundreds of times before with the same code*) is failing  deep in the docusign code. 

Any suggestions on what is going bump in the night?

*pre-`docusign-python-client` update

```
Traceback (most recent call last):
File "/var/task/handler.py", line 117, in get_templates
result = Template(api_client).get(event)
File "/var/task/template.py", line 152, in get
raise ex
File "/var/task/template.py", line 146, in get
Template.accountID, template_id).to_dict()
File "/var/task/docusign_esign/apis/templates_api.py", line 2291, in get
(data) = self.get_with_http_info(account_id, template_id, **kwargs)
File "/var/task/docusign_esign/apis/templates_api.py", line 2378, in get_with_http_info
collection_formats=collection_formats)
File "/var/task/docusign_esign/client/api_client.py", line 354, in call_api
_return_http_data_only, collection_formats, _preload_content, _request_timeout)
File "/var/task/docusign_esign/client/api_client.py", line 184, in __call_api
return_data = self.deserialize(r, response_type)
File "/var/task/docusign_esign/client/api_client.py", line 264, in deserialize
return self.__deserialize(data, response_type)
File "/var/task/docusign_esign/client/api_client.py", line 307, in __deserialize
return self.__deserialize_model(data, klass)
File "/var/task/docusign_esign/client/api_client.py", line 657, in __deserialize_model
setattr(instance, attr, self.__deserialize(value, attr_type))
File "/var/task/docusign_esign/client/api_client.py", line 307, in __deserialize
return self.__deserialize_model(data, klass)
File "/var/task/docusign_esign/client/api_client.py", line 657, in __deserialize_model
setattr(instance, attr, self.__deserialize(value, attr_type))
File "/var/task/docusign_esign/client/api_client.py", line 294, in __deserialize
klass = getattr(client, klass)
AttributeError: module 'docusign_esign.client' has no attribute 'UserInfo'
module 'docusign_esign.client' has no attribute 'UserInfo'
```

simplified code
```
from docusign_esign import TemplatesApi
template_api = TemplatesApi(Template.api_client)
def function_in_question():
    return template_api.get(accountID, template_id).to_dict()
```

**Comment by excenter** [comment]
Beyond just templates, I'm having issues around `"module 'docusign_esign.client' has no attribute 'UserInfo'"`

**Comment by LarryKlugerDS** [comment]
Which Python version? 
I have filed bug report DCM-3468

**Comment by excenter** [comment]
3.7.4 and 3.6.*

**Comment by Nickolay-Suslov** [comment]
Got the same problem

**Comment by aadarshjajodiaSB** [comment]
Relevant references in current code:

UserInfo model exists:
https://github.com/docusign/docusign-esign-python-client/blob/master/docusign_esign/models/user_info.py#L22

UserInfo is exported in package init:
https://github.com/docusign/docusign-esign-python-client/blob/master/docusign_esign/__init__.py#L548

Deserialization resolves non-OAuth model names from models (not client), which differs from the original failure path:
https://github.com/docusign/docusign-esign-python-client/blob/master/docusign_esign/client/api_client.py#L300-L314

Given the age of this report and no recent reproducible case on current versions, closing as stale. If anyone can still reproduce on the latest SDK, please open a new issue with:

SDK version
Python version
