### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by Spievat** [docusign/docusign-python-client#7]
### Context for the error:
Python Version 3.5.2
Access granted to the app through DocuSign OAuth authorization url? **Yes**

While running the [main script](https://github.com/docusign/docusign-python-client#usage) after configuring it for my DocuSign Sandbox account, I get the TypeError. 

### Traceback:
```
Traceback (most recent call last):
  File "testing.py", line 66, in <module>
    login_info = auth_api.login(api_password='true', include_account_id_guid='true')
  File "/Users/brady/.local/share/virtualenvs/Docusign-eC2R9qCp/lib/python3.5/site-packages/docusign_esign/apis/authentication_api.py", line 388, in login
    (data) = self.login_with_http_info(**kwargs)
  File "/Users/brady/.local/share/virtualenvs/Docusign-eC2R9qCp/lib/python3.5/site-packages/docusign_esign/apis/authentication_api.py", line 472, in login_with_http_info
    collection_formats=collection_formats)
  File "/Users/brady/.local/share/virtualenvs/Docusign-eC2R9qCp/lib/python3.5/site-packages/docusign_esign/api_client.py", line 373, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/Users/brady/.local/share/virtualenvs/Docusign-eC2R9qCp/lib/python3.5/site-packages/docusign_esign/api_client.py", line 208, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/Users/brady/.local/share/virtualenvs/Docusign-eC2R9qCp/lib/python3.5/site-packages/docusign_esign/api_client.py", line 282, in deserialize
    data = json.loads(response.data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

### Solution:
**Change this line:**
https://github.com/docusign/docusign-python-client/blob/ad71773452e4df3e500af93849d060718819df43/docusign_esign/api_client.py#L282

**To this:**
`data = json.loads(response.data.decode('utf-8'))`

**Which matches the pattern used here:**
https://github.com/docusign/docusign-python-client/blob/ad71773452e4df3e500af93849d060718819df43/docusign_esign/api_client.py#L119

Thank you, kindly!

**Comment by mmallis87** [comment]
@Spievat Thanks for the feedback. While your solution works for Python3, I'm not sure it will work in Python2. I think we should use conditional code for each version of Python. In case you wanna try it out, please submit a pull request.

**Comment by Spievat** [comment]
Yessir, you're right! We need a conditional for this to work with Python2. I'd love to submit a pull request, but I'm unable to per the [Contributing](https://github.com/docusign/docusign-python-client#contributing) section of this repo's README:

**"This SDK is auto-generated from OpenAPI specification file. For that reason, we actually do NOT accept pull requests. If you find a bug or have an idea that you want to see in the SDK, please open a new issue."**

Here's that conditional:

```
import sys

...

# fetch data from response object
try:
    # check Python's major version number
    if sys.version_info[0] < 3:
        data = json.loads(response.data)
    else:
        data = json.loads(response.data.decode('utf-8'))
except ValueError:
    data = response.data
```

**Comment by mmallis87** [comment]
Just merged the changes into master (we use PY3 constant from six package). A new Python package should be released in the upcoming days.

**Comment by mmallis87** [comment]
Sorry for the delay. version 1.0.3 was just deployed today.
